GET http://localhost:4000/
###

GET http://localhost:4000/api/restaurants/1444264026

###

POST http://localhost:4000/
Content-Type: application/json

{
    "name": "Joy",
    "address": "12th st",
    "operationHours": "9-5",
    "phoneNumber": "010-1234-5678",
    "imageURL": "sdfasf"

}

###
POST http://localhost:4000//api/signup
Content-Type: application/json

{
    "username": "JOJO",
    "password": "12345"
}

###
GET http://localhost:4000/api/user/users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTMyMGQ2MWM5ZmZjNjgwMGI1NTZiMTgiLCJpYXQiOjE3MDAyMjMxMDgsImV4cCI6MTcwMDQ4MjMwOH0.rQdIqi4vhO-7ilJGd7y7ra-KCyG-VxO2L1AlQFXACvQ


###

POST http://localhost:4000/api/user/login
Content-Type: application/json
Authorization: Bearer 1234

{
    "email": "HAHA@gmail.com",
    "password": "ThisisGood1!"
}

###1
GET http://localhost:4000/api/geocode/1444264026

###1
GET http://localhost:4000/api/restaurant/1444264026/address

####1
POST http://localhost:4000/api/user/signup
Content-Type: application/json
Authorization: Bearer 1234

{
    "email": "srestviv@gmail.com",
    "username": "Admin",
    "password": "ThisisGood1!",
    "role": "admin"
}

####1
POST http://localhost:4000/api/user/login
Content-Type: application/json
Authorization: Bearer 1234

{
    "email": "srestviv@gmail.com",
    "password": "ThisisGood1!"
}

###1
POST http://localhost:4000/api/review/64e7129db4214f2c5617157d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTNiNjA3MjRhNjhjNjI0NTYwY2MwYjYiLCJpYXQiOjE2OTkzNTcxNTcsImV4cCI6MTY5OTYxNjM1N30.xL0Q8x1waTPA6Te09yTFD7WCZQkzFiLwt1HUavP2b10

{
  "rating": "1",                
  "comment": "Bad restaurant!",  
  "memberId": "653b60724a68c624560cc0b6",  
  "restaurantId": "64e7129db4214f2c5617157d" 
}

####1
GET http://localhost:4000/api/review/restaurant/1444264026

####1
GET http://localhost:4000/api/user/65320d61c9ffc6800b556b18
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTMyMGQ2MWM5ZmZjNjgwMGI1NTZiMTgiLCJpYXQiOjE2OTc4NjA0MTQsImV4cCI6MTY5ODExOTYxNH0.nbAQ8k4m-xEhohaC3X5GdC4FeyivXNypfEZufV7brdo

###1
GET http://localhost:4000/api/review/restaurant/1444264026/members/65320d61c9ffc6800b556b18
